# Generated by Django 5.2.7 on 2025-10-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarymodel',
            old_name='salary',
            new_name='employee',
        ),
    ]
